---
services:
  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/GMT
    volumes:
      - wireshark:/config
    ports:
      - 3027:3000 #optional
      - 3028:3001 #optional
    restart: unless-stopped
volumes:
  wireshark: