---
services:
  vscodium:
    image: lscr.io/linuxserver/vscodium:latest
    container_name: vscodium
    cap_add:
      - IPC_LOCK
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - vscodium:/config
    ports:
      - 3311:3000
      - 3312:3001
    shm_size: "1gb"
    restart: unless-stopped
volumes:
  vscodium: