version: "3.6"
services:
    organizr:
        container_name: organizr
        hostname: organizr
        image: organizr/organizr:latest
        restart: unless-stopped
        ports:
            - 8098:80
        volumes:
            - organizr:/config
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
volumes:
  organizr: