version: "3.0"
services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    volumes:
      - /var/lib/docker/volumes/memos:/var/opt/memos
    ports:
      - 5230:5230
    restart: unless-stopped