---
services:
  wikijs:
    image: lscr.io/linuxserver/wikijs:latest
    container_name: wikijs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DB_TYPE=mysql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT} 
      - DB_NAME=${DB_NAME} 
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:
      - wikijs:/config
      - wikijs:/data
    ports:
      - 3000:3000
    restart: unless-stopped
volumes:
  wikijs: