version: "3.3"
services:
  pastr:
    container_name: pastr
    image: pastr
    restart: always
    ports:
      - "3330:3000"
    environment:
      - PASTR_HOST=http://localhost:3330
      - PASTR_KEY_LENGTH=4
    volumes:
      - pastr:/app/data.db
volumes:
  pastr: