---
services:
  synclounge:
    image: lscr.io/linuxserver/synclounge:latest
    container_name: synclounge
    environment:
      #- AUTH_LIST=plexuser1,plexuser2,email1,machineid1 #optional
    ports:
      - 8088:8088
    restart: unless-stopped