version: '3'
services:
  pwgen:
    image: jocxfin/pwgen:latest
    container_name: PwGen
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 5069 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    environment:
      - NO_API_CHECK=false
      - PW_LENGTH=12
      - PW_INCLUDE_UPPERCASE=true
      - PW_INCLUDE_DIGITS=true
      - PW_INCLUDE_SPECIAL=true
      - PW_EXCLUDE_HOMOGLYPHS=true
      - PP_WORD_COUNT=4
      - PP_CAPITALIZE=true
      - PP_SEPARATOR_TYPE=dash
    ports:
      - 5069:5069
    restart: on-failure:5
