---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/data:/config
     # - /path/to/tvseries:/tv #optional
     # - /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 8947:8989
    restart: unless-stopped