auth:
  - user: plex
    group: plex
    uid: 1000
    gid: 1000
    password: plexmedia
#  - user: baz
#    group: xxx
#    uid: 1100
#    gid: 1200
#    password_file: /run/secrets/baz_password

global:
  - "force user = plex"
  - "force group = plex"

share:
  - name: plex
    comment: Plex
    path: /samba/plex
    browsable: yes
    readonly: no
    guestok: yes
    veto: no
    recycle: yes
#  - name: share
#    path: /samba/share
#    browsable: yes
#    readonly: no
#    guestok: yes
#    writelist: foo
#    veto: no
#  - name: foo
#    path: /samba/foo
#    browsable: yes
#    readonly: no
#    guestok: no
#    validusers: foo
#    writelist: foo
#    veto: no
#    hidefiles: /_*/
#  - name: foo-baz
#    path: /samba/foo-baz
#    browsable: yes
#    readonly: no
#    guestok: no
#    validusers: foo,baz
#    writelist: foo,baz
#    veto: no