version: "3"

services:
  paste-bin:
    container_name: paste-bin
    image: ghcr.io/enchant97/hasty-paste:1
    restart: unless-stopped
    volumes:
      - hastypasty:/app/data
    ports:
      - 8372:8000
    environment:
      - "TIME_ZONE=Europe/London"

volumes:
  hastypasty: