version: "3.3"
services:
  shlink:
    container_name: my_shlink
    ports:
      - 8438:8080
    environment:
      - DEFAULT_DOMAIN=s.test
      - IS_HTTPS_ENABLED=true
      # - GEOLITE_LICENSE_KEY=kjh23ljkbndskj345
      - DB_DRIVER=mysql
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    image: shlinkio/shlink:stable