---
services:
  libreoffice:
    image: lscr.io/linuxserver/libreoffice:latest
    container_name: libreoffice
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/GMT
    volumes:
      - config:/config
    ports:
      - 3451:3000
      - 3452:3001
    restart: unless-stopped
volumes:
  config: