networks:
  tugtainer:
    driver: bridge
services:
  app:
    container_name: tugtainer
    image: quenary/tugtainer:latest
    volumes:
      - tugtainer_data:/tugtainer
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - tugtainer
    ports:
      - '9412:80'
volumes:
  tugtainer_data: